<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="CsCheck" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Money.Application\Money.Application.csproj" />
    <ProjectReference Include="..\..\src\Money.Infrastructure\Money.Infrastructure.csproj" />
    <ProjectReference Include="..\Money.TestSupport\Money.TestSupport.csproj" />
  </ItemGroup>

</Project>
